# Gunakan image Node.js sebagai dasar
FROM node:16-alpine

# Set direktori kerja di dalam kontainer
WORKDIR /app

# Salin package.json dan package-lock.json untuk menginstal dependencies
COPY package* .
RUN npm i

# Salin kode client ke dalam kontainer
COPY . .

RUN npm run build
# Expose port yang akan digunakan oleh aplikasi
EXPOSE 3000

# Command untuk menjalankan aplikasi
#CMD ["npm", "run", "dev"]
CMD ["npm", "run", "preview"]
