# Gunakan image Node.js sebagai dasar
FROM node:16-alpine

# Set direktori kerja di dalam kontainer
WORKDIR /app

# Salin package.json dan package-lock.json untuk menginstal dependencies
COPY package* .
RUN apk add --no-cache python3
RUN npm i

# Salin kode backend ke dalam kontainer
COPY  . .

# Expose port yang akan digunakan oleh aplikasi
EXPOSE 3001

# Command untuk menjalankan aplikasi
CMD ["npm", "run", "dev"]
# CMD ["npm", "start"]
